"""
Queen Agent — VirtualAgent module.

Each VirtualAgent is an autonomous research agent that runs as 4 daemon
threads inside the Queen's own Railway process. No external hosting needed.

Threads:
  1. heartbeat  — re-register in P2PCLAW (every 60 s)
  2. research   — generate & publish papers (soul-timed interval)
  3. validation — peer-review mempool papers (soul-timed interval)
  4. social     — post insights to P2PCLAW chat (soul-timed interval)

The agent's identity, domains, LLM, and timing come from its soul dict.
Papers use the soul's domains list and papers_system_prompt.
"""

import os
import random
import re
import threading
import time
import traceback
from datetime import datetime, timezone
from typing import Optional, Callable

import httpx

import llm as llm_module

# ── P2PCLAW API ───────────────────────────────────────────────────────────────
P2P_API = os.getenv("P2P_API", "https://api-production-ff1b.up.railway.app")
_HTTP_TIMEOUT = 30.0


class VirtualAgent:
    """
    A fully autonomous research agent running in the Queen's process.
    Parameterized by a soul dict generated by soul.py.
    """

    def __init__(self, soul: dict, log_callback: Optional[Callable[[str], None]] = None):
        # Identity
        self.soul        = soul
        self.codename    = soul["codename"]
        self.agent_id    = soul["agent_id"]
        self.full_name   = soul["full_name"]
        self.specialty   = soul["specialty"]
        self.mission     = soul.get("mission", "")
        self.interests   = soul.get("interests", self.specialty)
        self.personality = soul.get("personality", "")
        self.writing_style = soul.get("writing_style", "")
        self.agent_url   = soul.get("agent_url", "")
        self.color_scheme = soul.get("color_scheme", ["#0f1117", "#60a5fa"])

        # Research domains — list of [title, inv-id] pairs
        self.domains: list[list[str]] = soul.get("domains", [])

        # LLM config (all virtual agents share the Queen's env vars)
        self.llm_provider = soul.get("llm_provider", "groq")
        self.llm_model    = soul.get("llm_model", "llama-3.3-70b-versatile")
        self.llm_env_var  = soul.get("llm_env_var", "GROQ_KEY")

        # Paper generation system prompt
        self._system_prompt = soul.get(
            "papers_system_prompt",
            f"You are {self.full_name}, an autonomous researcher on the P2PCLAW network."
        )

        # Timing — deterministic from soul (already computed in soul.py)
        self._t_research   = soul.get("research_interval",   900)
        self._t_validation = soul.get("validation_interval", 600)
        self._t_social     = soul.get("social_interval",    1800)
        self._d_heartbeat  = soul.get("heartbeat_start_delay",   5)
        self._d_research   = soul.get("research_start_delay",   45)
        self._d_validation = soul.get("validation_start_delay", 120)
        self._d_social     = soul.get("social_start_delay",     240)
        self._j_research   = soul.get("jitter_research",         60)
        self._j_validation = soul.get("jitter_validation",       30)
        self._j_social     = soul.get("jitter_social",          120)

        # Runtime state
        self._running  = False
        self._threads: list[threading.Thread] = []
        self._log_cb   = log_callback or (lambda msg: print(msg))

        self.papers_published  = 0
        self.validations_done  = 0
        self.messages_sent     = 0
        self.rank              = "NEWCOMER"
        self.last_action       = "Initialized"
        self.log_history: list[str] = []
        self._validated_ids: set[str] = set()
        self._recent_topics: list[str] = []

        # Evolution tracking
        self.born_at = time.time()
        self.fitness_history: list[tuple] = []  # (timestamp, score)

        # Own httpx client
        self._http = httpx.Client(
            timeout=_HTTP_TIMEOUT,
            follow_redirects=True,
            headers={"User-Agent": f"OpenCLAW-VirtualAgent/{self.agent_id}"},
        )

    # ── Lifecycle ──────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Launch 4 daemon threads. Idempotent — safe to call on restart."""
        if self._running:
            return
        self._running = True
        self._threads = []  # reset thread list on restart

        loops = [
            ("heartbeat",  self._heartbeat_loop,  self._d_heartbeat),
            ("research",   self._research_loop,   self._d_research),
            ("validation", self._validation_loop, self._d_validation),
            ("social",     self._social_loop,     self._d_social),
        ]
        for name, fn, delay in loops:
            t = threading.Thread(
                target=fn,
                args=(delay,),
                name=f"va-{self.codename}-{name}",
                daemon=True,
            )
            t.start()
            self._threads.append(t)

        self._log(f"🌱 {self.codename} ({self.full_name}) started — {len(self._threads)} threads")

    def stop(self) -> None:
        self._running = False
        try:
            self._http.close()
        except Exception:
            pass
        self._log(f"🛑 {self.codename} stopped")

    def is_alive(self) -> bool:
        """True if at least one thread is still running."""
        return self._running and any(t.is_alive() for t in self._threads)

    def threads_alive(self) -> int:
        return sum(t.is_alive() for t in self._threads)

    def get_fitness_score(self) -> float:
        """Composite fitness score for evolution selection."""
        age_hours    = max((time.time() - self.born_at) / 3600, 0.1)
        papers_rate  = self.papers_published / age_hours
        rank_bonus   = {
            "NEWCOMER":           0.0,
            "JUNIOR_RESEARCHER":  2.0,
            "RESEARCHER":         5.0,
            "SENIOR_RESEARCHER": 10.0,
            "PRINCIPAL":         20.0,
        }.get(self.rank, 0.0)
        score = (
            papers_rate * 10.0          +
            self.validations_done * 0.8 +
            self.messages_sent    * 0.2 +
            self.threads_alive()  * 1.5 +
            rank_bonus
        )
        # Record in history (cap at 100 entries)
        self.fitness_history.append((time.time(), round(score, 2)))
        if len(self.fitness_history) > 100:
            self.fitness_history = self.fitness_history[-100:]
        return score

    def get_status(self) -> dict:
        return {
            "agent_id":         self.agent_id,
            "codename":         self.codename,
            "full_name":        self.full_name,
            "specialty":        self.specialty,
            "mission":          self.mission,
            "llm":              f"{self.llm_provider}/{self.llm_model}",
            "papers_published": self.papers_published,
            "validations_done": self.validations_done,
            "messages_sent":    self.messages_sent,
            "rank":             self.rank,
            "last_action":      self.last_action,
            "threads_alive":    self.threads_alive(),
            "status":           "HEALTHY" if self.is_alive() else "DEAD",
            "agent_url":        self.agent_url,
            "color_scheme":     self.color_scheme,
            "fitness":          round(self.get_fitness_score(), 2),
        }

    # ── Logging ───────────────────────────────────────────────────────────────

    def _log(self, msg: str) -> None:
        ts = datetime.now(timezone.utc).strftime("%H:%M:%S UTC")
        entry = f"[{ts}][{self.codename}] {msg}"
        self.log_history.append(entry)
        if len(self.log_history) > 200:
            self.log_history = self.log_history[-200:]
        self.last_action = msg
        self._log_cb(entry)

    # ── Thread: Heartbeat ──────────────────────────────────────────────────────

    def _heartbeat_loop(self, initial_delay: int) -> None:
        time.sleep(initial_delay)
        self._register()

        while self._running:
            try:
                self._p2p_post("/quick-join", {
                    "agentId":      self.agent_id,
                    "name":         self.full_name,
                    "type":         "ai-agent",
                    "role":         "researcher",
                    "interests":    self.interests,
                    "capabilities": ["publish", "validate", "chat"],
                })
            except Exception:
                pass
            time.sleep(60)

    def _register(self) -> None:
        try:
            res = self._p2p_post("/quick-join", {
                "agentId":      self.agent_id,
                "name":         self.full_name,
                "type":         "ai-agent",
                "role":         "researcher",
                "interests":    self.interests,
                "capabilities": ["publish", "validate", "chat"],
            })
            self._log(f"✅ Registered in P2PCLAW — rank: {res.get('rank', 'NEWCOMER')}")

            # Announce arrival
            self._p2p_post("/chat", {
                "message": (
                    f"🤖 **{self.full_name}** online — 24/7 autonomous researcher. "
                    f"Specialty: {self.specialty}. Mission: {self.mission[:100]}... "
                    f"Agent: `{self.agent_id}` | LLM: {self.llm_model}"
                ),
                "sender": self.agent_id,
            })
        except Exception as e:
            self._log(f"⚠️ Registration failed: {e} — proceeding anyway")

        # Try to get rank info
        try:
            r = self._http.get(
                f"{P2P_API}/agent-rank",
                params={"agent": self.agent_id},
                timeout=15.0,
            )
            if r.status_code == 200:
                info = r.json()
                self.rank = info.get("rank", "NEWCOMER")
                self.papers_published = info.get("contributions", self.papers_published)
        except Exception:
            pass

    # ── Thread: Research (publish papers) ─────────────────────────────────────

    def _research_loop(self, initial_delay: int) -> None:
        time.sleep(initial_delay)

        while self._running:
            try:
                self._do_research_cycle()
            except Exception:
                self._log(f"❌ Research error: {traceback.format_exc()[-200:]}")

            jitter = random.randint(-self._j_research, self._j_research)
            time.sleep(max(300, self._t_research + jitter))

    def _do_research_cycle(self) -> None:
        self._log("🔬 Starting research cycle...")

        # Gather context from recent network papers
        context = self._gather_context()

        # Generate paper (up to 3 attempts)
        paper = None
        for attempt in range(1, 4):
            try:
                self._log(f"📝 Generating paper (attempt {attempt}/3)...")
                paper = self._generate_paper(context)
                self._log(f"Draft: '{paper['title'][:70]}...' ({len(paper['content'].split())} words)")
                break
            except Exception as e:
                self._log(f"⚠️ Generation attempt {attempt} failed: {e}")
                time.sleep(15 * attempt)

        if paper is None:
            self._log("❌ Paper generation failed after all retries")
            return

        # Publish
        self._log("📤 Publishing to P2PCLAW...")
        try:
            res = self._p2p_post("/publish-paper", paper, timeout=60.0)
        except Exception as e:
            self._log(f"❌ Publish failed: {e}")
            return

        if res.get("success"):
            self.papers_published += 1
            pid    = res.get("paperId", "?")
            words  = res.get("word_count", "?")
            status = res.get("status", "MEMPOOL")
            self._log(f"✅ Published #{self.papers_published} | ID: {pid} | {words} words | {status}")

            self._recent_topics.append(paper["title"])
            if len(self._recent_topics) > 10:
                self._recent_topics = self._recent_topics[-10:]

            try:
                self._p2p_post("/chat", {
                    "message": (
                        f"📢 New paper: **'{paper['title'][:90]}'** "
                        f"| `{paper.get('investigation_id', 'general')}` "
                        f"| {words} words | Mempool"
                    ),
                    "sender": self.agent_id,
                })
            except Exception:
                pass

            # Refresh rank
            try:
                r = self._http.get(f"{P2P_API}/agent-rank",
                                   params={"agent": self.agent_id}, timeout=10.0)
                if r.status_code == 200:
                    self.rank = r.json().get("rank", self.rank)
            except Exception:
                pass
        else:
            self._log(f"⚠️ Publish rejected: {res.get('error', 'unknown')} — {res.get('hint', '')}")

    def _generate_paper(self, context: str) -> dict:
        """Generate a research paper using the soul's domains and system prompt."""
        if not self.domains:
            raise ValueError("No domains in soul")

        topic, inv_id = random.choice(self.domains)
        date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

        ctx_block = (
            f"\n\n**Context — recent P2PCLAW papers:**\n{context}\n"
            if context else ""
        )

        prompt = f"""Write a complete, rigorous research paper on the following topic.
{ctx_block}
**Topic:** {topic}

Use this EXACT Markdown structure:

# [Specific, insightful title]

**Investigation:** {inv_id}
**Agent:** {self.agent_id}
**Date:** {date}

## Abstract

[150–200 words. State the research problem, methodology, key findings.]

## Introduction

[250–350 words. Context, motivation, 3 concrete contributions, 3–4 citations.]

## Background

[200–300 words. Key concepts, related work, prerequisites.]

## Core Analysis

[400–500 words. Main theoretical or empirical contribution.
Include equations, proofs, algorithms, or experimental data as appropriate.
Use the distinctive style of {self.specialty}.]

## Results and Discussion

[300–400 words. Findings, implications, comparison with prior work.
Include at least one table or structured list of results.]

## Limitations and Future Work

[150–200 words. Honest assessment, open problems, next steps.]

## Conclusion

[100–150 words. Summary and takeaway.]

## References

[10–14 realistic references in standard format.]

---
Writing style: {self.writing_style}
Minimum: 800 words of substantive content.
Be specific, use precise terminology from {self.specialty}."""

        content = llm_module.complete(
            messages=[
                {"role": "system", "content": self._system_prompt},
                {"role": "user",   "content": prompt},
            ],
            max_tokens=4500,
            temperature=0.73,
        )

        # Inject metadata if missing
        if f"**Investigation:** {inv_id}" not in content:
            content = re.sub(
                r"(# .+?\n)",
                f"\\1\n**Investigation:** {inv_id}\n**Agent:** {self.agent_id}\n**Date:** {date}\n",
                content, count=1,
            )

        # Extract title
        title = topic
        m = re.search(r"^# (.+)$", content, re.MULTILINE)
        if m:
            title = m.group(1).strip()

        word_count = len(content.split())
        if word_count < 520:  # API requires 500 for final tier; 520 adds safety margin
            raise ValueError(f"Paper too short: {word_count} words (need 520+)")

        return {
            "title":            title,
            "content":          content,
            "investigation_id": inv_id,
            "author":           self.full_name,
            "agentId":          self.agent_id,
            "tier":             "final",
        }

    def _gather_context(self) -> str:
        try:
            r = self._http.get(f"{P2P_API}/latest-papers", params={"limit": 5}, timeout=15.0)
            if r.status_code == 200:
                papers = r.json()
                titles = [p.get("title", "") for p in papers if p.get("title")]
                if titles:
                    self._log(f"📚 Context: {len(titles)} recent papers")
                    return "Recent network research: " + " | ".join(titles[:4])
        except Exception:
            pass
        return ""

    # ── Thread: Validation ─────────────────────────────────────────────────────

    def _validation_loop(self, initial_delay: int) -> None:
        time.sleep(initial_delay)

        while self._running:
            try:
                self._do_validation_cycle()
            except Exception as e:
                self._log(f"⚠️ Validation error: {e}")

            jitter = random.randint(-self._j_validation, self._j_validation)
            time.sleep(max(120, self._t_validation + jitter))

    def _do_validation_cycle(self) -> None:
        try:
            r = self._http.get(f"{P2P_API}/mempool", params={"limit": 30}, timeout=15.0)
            if r.status_code != 200:
                return
            mempool = r.json()
            if not isinstance(mempool, list):
                return
        except Exception as e:
            self._log(f"⚠️ Mempool fetch failed: {e}")
            return

        # Filter: skip own papers and already-validated ones
        candidates = [
            p for p in mempool
            if p.get("author_id") != self.agent_id
            and p.get("id") not in self._validated_ids
        ]

        if not candidates:
            self._log("📭 No new mempool papers to validate")
            return

        to_validate = random.sample(candidates, min(3, len(candidates)))
        self._log(f"🔍 Reviewing {len(to_validate)} paper(s)...")

        for paper in to_validate:
            self._validate_one(paper)
            time.sleep(10)

    def _validate_one(self, paper: dict) -> None:
        pid     = paper.get("id", "?")
        title   = paper.get("title", "Untitled")
        content = paper.get("content") or ""   # mempool returns content:null for metadata-only entries

        try:
            approve, score, reason = self._evaluate_paper(title, content)
        except Exception as e:
            self._log(f"⚠️ Eval failed for {pid}: {e}")
            approve, score, reason = True, 0.75, "Fallback approval"

        try:
            res = self._p2p_post("/validate-paper", {
                "paperId":     pid,
                "agentId":     self.agent_id,
                "result":      approve,
                "occam_score": round(score, 3),
            })
        except Exception as e:
            self._log(f"⚠️ Validate request failed for {pid}: {e}")
            return

        if res.get("success"):
            self._validated_ids.add(pid)
            self.validations_done += 1
            icon = "✅" if approve else "❌"
            self._log(f"{icon} Validated '{title[:55]}' | score={score:.2f} | {reason[:60]}")
        else:
            self._log(f"ℹ️ Validation skipped for {pid}: {res.get('error', 'see API')}")

    def _evaluate_paper(self, title: str, content: str) -> tuple:
        """LLM-based paper quality evaluation. Returns (approve, score, reason)."""
        import json as _json
        resp = llm_module.complete(
            messages=[
                {
                    "role": "system",
                    "content": (
                        f"You are {self.full_name}, an expert in {self.specialty}, "
                        "performing peer review. Respond ONLY with valid JSON."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Evaluate this paper for quality.\n\n"
                        f"Title: {title}\nExcerpt: {content[:1200]}\n\n"
                        'Respond ONLY: {"approve": true/false, "score": 0.0-1.0, "reason": "one sentence"}\n'
                        "Approve if: technically substantive, has analysis/proofs/data, >=400 words.\n"
                        "Reject if: placeholder text, vague generalizations, no depth."
                    ),
                },
            ],
            max_tokens=150,
            temperature=0.2,
        )
        try:
            m = re.search(r"\{[^{}]+\}", resp, re.DOTALL)
            if m:
                data = _json.loads(m.group())
                return (
                    bool(data.get("approve", True)),
                    max(0.0, min(1.0, float(data.get("score", 0.82)))),
                    str(data.get("reason", "")),
                )
        except Exception:
            pass
        return True, 0.80, "Automated review"

    # ── Thread: Social ─────────────────────────────────────────────────────────

    def _social_loop(self, initial_delay: int) -> None:
        time.sleep(initial_delay)

        while self._running:
            try:
                self._do_social()
            except Exception as e:
                self._log(f"⚠️ Social error: {e}")

            jitter = random.randint(-self._j_social, self._j_social)
            time.sleep(max(600, self._t_social + jitter))

    def _do_social(self) -> None:
        # Get recent paper titles for context
        recent_titles: list[str] = []
        try:
            r = self._http.get(f"{P2P_API}/latest-papers", params={"limit": 6}, timeout=15.0)
            if r.status_code == 200:
                recent_titles = [p.get("title", "") for p in r.json() if p.get("title")]
        except Exception:
            pass

        titles_block = "\n".join(f"- {t}" for t in recent_titles[:5]) or "(no recent papers)"

        try:
            msg = llm_module.complete(
                messages=[
                    {
                        "role": "system",
                        "content": (
                            f"You are {self.full_name}, a {self.specialty} expert "
                            f"on a P2P research network. {self.personality} "
                            "Write ONE sharp insight, observation, or open question "
                            "(2-4 sentences, no fluff). Be specific. "
                            f"End with: — {self.full_name}"
                        ),
                    },
                    {
                        "role": "user",
                        "content": (
                            f"Recent P2PCLAW papers:\n{titles_block}\n\n"
                            f"Write a thoughtful observation from your perspective "
                            f"as a {self.specialty} researcher."
                        ),
                    },
                ],
                max_tokens=220,
                temperature=0.75,
            )

            res = self._p2p_post("/chat", {
                "message": f"💡 {msg.strip()}",
                "sender":  self.agent_id,
            })
            if res.get("success"):
                self.messages_sent += 1
                self._log(f"💬 Posted insight: '{msg[:80]}...'")

        except Exception as e:
            self._log(f"⚠️ Social post failed: {e}")

    # ── HTTP helper ────────────────────────────────────────────────────────────

    def _p2p_post(self, path: str, body: dict, timeout: float = _HTTP_TIMEOUT) -> dict:
        r = self._http.post(f"{P2P_API}{path}", json=body, timeout=timeout)
        r.raise_for_status()
        return r.json()
